"""
HTML Report Generator.

Produces a standalone HTML file summarizing:
- Attack Surface (Dispatch Table, IOCTLs, Devices)
- Fuzzing Coverage (if available)
- Triage Results (Crash Clusters)
"""
import json
from typing import Dict, Any, Optional
from pathlib import Path
from datetime import datetime

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logic Flow Analysis Report</title>
    <style>
        :root {{
            --bg-dark: #1a1a2e;
            --bg-card: #16213e;
            --accent: #0f3460;
            --highlight: #e94560;
            --text: #eaeaea;
            --text-muted: #8b8b8b;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: 'Segoe UI', system-ui, sans-serif;
            background: var(--bg-dark);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ color: var(--highlight); margin-bottom: 1rem; font-size: 2rem; }}
        h2 {{ color: var(--text); margin: 2rem 0 1rem; border-left: 4px solid var(--highlight); padding-left: 1rem; }}
        .card {{
            background: var(--bg-card);
            border-radius: 12px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }}
        .stat-item {{
            background: var(--accent);
            padding: 1rem;
            border-radius: 8px;
            text-align: center;
        }}
        .stat-value {{ font-size: 2rem; font-weight: bold; color: var(--highlight); }}
        .stat-label {{ color: var(--text-muted); font-size: 0.9rem; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
        }}
        th, td {{
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid var(--accent);
        }}
        th {{ background: var(--accent); color: var(--highlight); }}
        tr:hover {{ background: rgba(233, 69, 96, 0.1); }}
        .code {{ font-family: 'Consolas', monospace; background: var(--accent); padding: 0.2rem 0.5rem; border-radius: 4px; }}
        .badge {{
            display: inline-block;
            padding: 0.2rem 0.6rem;
            border-radius: 12px;
            font-size: 0.8rem;
            font-weight: bold;
        }}
        .badge-buffered {{ background: #2ecc71; color: #000; }}
        .badge-direct {{ background: #f39c12; color: #000; }}
        .badge-neither {{ background: #e74c3c; color: #fff; }}
        .footer {{ text-align: center; color: var(--text-muted); margin-top: 2rem; font-size: 0.8rem; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 Logic Flow Analysis Report</h1>
        <p style="color: var(--text-muted);">Generated: {timestamp}</p>
        
        <h2>📊 Summary</h2>
        <div class="card">
            <div class="stats-grid">
                <div class="stat-item">
                    <div class="stat-value">{num_dispatch}</div>
                    <div class="stat-label">Dispatch Handlers</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">{num_ioctls}</div>
                    <div class="stat-label">IOCTLs Detected</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">{num_devices}</div>
                    <div class="stat-label">Device Objects</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">{num_crashes}</div>
                    <div class="stat-label">Unique Crashes</div>
                </div>
            </div>
        </div>
        
        <h2>🎯 Attack Surface - Dispatch Table</h2>
        <div class="card">
            <table>
                <tr><th>Major Function</th><th>Handler</th><th>Address</th><th>IRQL</th></tr>
                {dispatch_rows}
            </table>
        </div>
        
        <h2>🔢 IOCTLs</h2>
        <div class="card">
            {ioctl_section}
        </div>
        
        <h2>💥 Crash Triage</h2>
        <div class="card">
            {triage_section}
        </div>
        
        <div class="footer">
            Generated by Logic Flow Analyzer &bull; Windows Kernel Analysis Tool
        </div>
    </div>
</body>
</html>
"""

MAJOR_FUNCTION_NAMES = {
    0: "IRP_MJ_CREATE",
    1: "IRP_MJ_CREATE_NAMED_PIPE",
    2: "IRP_MJ_CLOSE",
    3: "IRP_MJ_READ",
    4: "IRP_MJ_WRITE",
    9: "IRP_MJ_FLUSH_BUFFERS",
    14: "IRP_MJ_DEVICE_CONTROL",
    15: "IRP_MJ_INTERNAL_DEVICE_CONTROL",
    16: "IRP_MJ_SHUTDOWN",
    18: "IRP_MJ_CLEANUP",
    23: "IRP_MJ_PNP",
    22: "IRP_MJ_POWER",
}


class HTMLReportGenerator:
    """Generates HTML reports from analysis data."""
    
    def __init__(self):
        self.interface_data: Dict[str, Any] = {}
        self.triage_data: Dict[str, Any] = {}
    
    def load_interface(self, path_or_data):
        """Load interface data from file or dict."""
        if isinstance(path_or_data, dict):
            self.interface_data = path_or_data
        else:
            with open(path_or_data, 'r') as f:
                self.interface_data = json.load(f)
    
    def load_triage(self, path_or_data):
        """Load triage data from file or dict."""
        if isinstance(path_or_data, dict):
            self.triage_data = path_or_data
        else:
            with open(path_or_data, 'r') as f:
                self.triage_data = json.load(f)
    
    def generate(self, output_path: str) -> str:
        """Generate HTML report and save to file."""
        dispatch_table = self.interface_data.get('dispatch_table', [])
        ioctls = self.interface_data.get('ioctls', [])
        devices = self.interface_data.get('devices', [])
        
        clusters = self.triage_data.get('clusters', {})
        
        # Build dispatch rows
        dispatch_rows = ""
        for entry in dispatch_table:
            mj = entry.get('major_function', -1)
            mj_name = MAJOR_FUNCTION_NAMES.get(mj, f"IRP_MJ_{mj}")
            handler = entry.get('handler_name', 'unknown')
            addr = hex(entry.get('handler_ea', 0))
            irql = entry.get('irql', 'PASSIVE')
            dispatch_rows += f"<tr><td>{mj_name}</td><td class='code'>{handler}</td><td class='code'>{addr}</td><td>{irql}</td></tr>\n"
        
        if not dispatch_rows:
            dispatch_rows = "<tr><td colspan='4'>No dispatch handlers found</td></tr>"
        
        # Build IOCTL section
        if ioctls:
            ioctl_rows = ""
            for ioctl in ioctls:
                code = ioctl.get('code', 0)
                method = ioctl.get('method', 'UNKNOWN')
                badge_class = 'badge-buffered' if 'BUFFERED' in method else ('badge-direct' if 'DIRECT' in method else 'badge-neither')
                ioctl_rows += f"<tr><td class='code'>{hex(code)}</td><td><span class='badge {badge_class}'>{method}</span></td><td class='code'>{hex(ioctl.get('handler_ea', 0))}</td></tr>\n"
            ioctl_section = f"<table><tr><th>Code</th><th>Method</th><th>Handler</th></tr>{ioctl_rows}</table>"
        else:
            ioctl_section = "<p>No IOCTLs detected. Run analysis with full instruction dump enabled.</p>"
        
        # Build triage section
        if clusters:
            triage_rows = ""
            for sig, files in clusters.items():
                triage_rows += f"<tr><td class='code'>{sig[:50]}...</td><td>{len(files)}</td></tr>\n"
            triage_section = f"<table><tr><th>Signature</th><th>Count</th></tr>{triage_rows}</table>"
        else:
            triage_section = "<p>No crash data available. Run fuzzing and triage first.</p>"
        
        # Fill template
        html = HTML_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            num_dispatch=len(dispatch_table),
            num_ioctls=len(ioctls),
            num_devices=len(devices),
            num_crashes=len(clusters),
            dispatch_rows=dispatch_rows,
            ioctl_section=ioctl_section,
            triage_section=triage_section
        )
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        return output_path
